name: "Sphinx: Render docs"

on: 
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install latexmk
      run: |
        sudo apt-get update -y
        sudo apt-get install latexmk -y
        latexmk
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make latexpdf"