name: "Sphinx: Render docs"

on: 
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: ""
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: ""
        pre-build-command: "sudo apt update -y && sudo apt install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make latexpdf"